apiVersion: v2
name: helm-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
- name: node01
  repository: file://charts/node01
  version: 0.1.0
  condition: node01.enabled
- name: pyhon01
  repository: file://charts/python01
  version: 0.1.0
  condition: python01.enabled
- name: gradle-sample-app
  repository: file://charts/gradle-sample-app
  version: 0.1.0
  condition: gradle-sample-app.enabled
